/*
 * EscapeManager
 * Dies ist die Dokumentation des REST API des EscapeManager
 *
 * OpenAPI spec version: 0.0.3
 * Contact: yvo.vonkaenel@students.ffhs.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ch.ffhs.pa5.escapeconnect.bean;


import java.util.Objects;


import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;



import javax.validation.constraints.*;




/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaJerseyDIServerCodegen", date = "2019-10-16T16:22:47.544870800+02:00[Europe/Berlin]")
public class InlineResponse200   {
  
    
      
  
  @JsonProperty("byteswritten")
  
  
  
  
  private Integer byteswritten = null;
  

  
    
      
  
  @JsonProperty("bytestotal")
  
  
  
  
  private Integer bytestotal = null;
  

  
    
      
  
  @JsonProperty("status")
  
  
  
  
  private Integer status = null;
  

  
  
  
  public InlineResponse200 byteswritten(Integer byteswritten) {
    this.byteswritten = byteswritten;
    return this;
  }
  
  

  
  /**
  
  
   * Get byteswritten
  
  
  
   * @return byteswritten
   **/
 
  
  @JsonProperty("byteswritten")
  
  @ApiModelProperty(value = "")

  public Integer getByteswritten() {
    return byteswritten;
  }
  

  public void setByteswritten(Integer byteswritten) {
    this.byteswritten = byteswritten;
  }
  

  
  
  public InlineResponse200 bytestotal(Integer bytestotal) {
    this.bytestotal = bytestotal;
    return this;
  }
  
  

  
  /**
  
  
   * Get bytestotal
  
  
  
   * @return bytestotal
   **/
 
  
  @JsonProperty("bytestotal")
  
  @ApiModelProperty(value = "")

  public Integer getBytestotal() {
    return bytestotal;
  }
  

  public void setBytestotal(Integer bytestotal) {
    this.bytestotal = bytestotal;
  }
  

  
  
  public InlineResponse200 status(Integer status) {
    this.status = status;
    return this;
  }
  
  

  
  /**
  
   * updatestatus gemäss https://homieiot.github.io/homie-esp8266/docs/develop-v3/others/ota-configuration-updates/
  
  
  
  
   * @return status
   **/
 
  
  @JsonProperty("status")
  
  @ApiModelProperty(value = "updatestatus gemäss https://homieiot.github.io/homie-esp8266/docs/develop-v3/others/ota-configuration-updates/")

  public Integer getStatus() {
    return status;
  }
  

  public void setStatus(Integer status) {
    this.status = status;
  }
  

  


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.byteswritten, inlineResponse200.byteswritten) &&
        Objects.equals(this.bytestotal, inlineResponse200.bytestotal) &&
        Objects.equals(this.status, inlineResponse200.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(byteswritten, bytestotal, status);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    byteswritten: ").append(toIndentedString(byteswritten)).append("\n");
    sb.append("    bytestotal: ").append(toIndentedString(bytestotal)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}



