/*
 * EscapeManager
 * Dies ist die Dokumentation des REST API des EscapeManager
 *
 * OpenAPI spec version: 0.0.3
 * Contact: yvo.vonkaenel@students.ffhs.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.ffhs.pa5.escapeconnect.bean;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.*;

/** Anzuzeigender Wert */
@ApiModel(description = "Anzuzeigender Wert")
@javax.annotation.Generated(
    value = "io.swagger.codegen.languages.java.JavaJerseyDIServerCodegen",
    date = "2019-10-16T16:22:47.544870800+02:00[Europe/Berlin]")
public class Value {

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("label")
  private String label = null;

  @JsonProperty("value")
  private String value = null;

  public Value id(Integer id) {
    this.id = id;
    return this;
  }

  /**
   * id des Anzeigewertes
   *
   * @return id
   */
  @JsonProperty("id")
  @ApiModelProperty(required = true, value = "id des Anzeigewertes")
  @NotNull
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Value label(String label) {
    this.label = label;
    return this;
  }

  /**
   * Label des Wertes
   *
   * @return label
   */
  @JsonProperty("label")
  @ApiModelProperty(required = true, value = "Label des Wertes")
  @NotNull
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public Value value(String value) {
    this.value = value;
    return this;
  }

  /**
   * Anzeigewert
   *
   * @return value
   */
  @JsonProperty("value")
  @ApiModelProperty(value = "Anzeigewert")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, label, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Value {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }


  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
